In [1]:
import pandas as pd
from sklearn.utils import shuffle

In [2]:
data=pd.read_csv('yorumlar_liste.csv',encoding='iso-8859-9')

In [3]:
data.loc[data['puan'] > 0.7, 'puan'] = 1.0

In [4]:
data.loc[data['puan'] < 0.5, 'puan'] = 0.0

In [5]:
df_1 = data[data.puan > 0.9]

In [6]:
df_1

                                                   yorum  puan
0                       bataryasi için aldım. kullanışlı   1.0
1      Ürün dış  görünüşü  çok  güzel..kamerada iyi.....   1.0
2                          evet çok şık ve çok özellikli   1.0
4      güvenilir satıcı Samsung m31s telefonu gayet g...   1.0
5      urun gercekten guzel arkadaslar ben bu insanla...   1.0
...                                                  ...   ...
50366                             Kaliteli ve kullanışlı   1.0
50367          kurulumu paketleme harika düşünmeden alın   1.0
50368                               kurulumu çok pratik.   1.0
50369                 üründen memnun kaldık.teşekkürler.   1.0
50371  Ürün şahane bir şekilde geldi. Üzerine 2 tane ...   1.0

[43302 rows x 2 columns]

In [7]:
df_0 = data[data.puan < 0.1]

In [8]:
df_0

                                                   yorum  puan
3      ne batarya ne kamera anlatılanlara aldanmayın ...   0.0
15     Alacak arkadaşlara önemli hatırlatma fatura gö...   0.0
23     Daha öncede alışveriş yapmıştım  çok geç kargo...   0.0
45     2 ay içerisinde 2 kez servise gönderilen bir c...   0.0
81     İşlemcisi kötü hiç bir uygulama açık değilken ...   0.0
...                                                  ...   ...
50047                      Delik geldiği için beğenmedim   0.0
50064  Ambalaj patlayan naylonla  yapılmış güzel  edi...   0.0
50197              Gelmeyen ürünle ilgili yorum mu olur.   0.0
50317  Yazılan nota ve telefon konuşmasına rağmen açı...   0.0
50340  denemek için 1 ad aldım ürün güzel fakat profi...   0.0

[4642 rows x 2 columns]

In [9]:
df=pd.concat([df_0,df_1],ignore_index=True)

In [10]:
df

                                                   yorum  puan
0      ne batarya ne kamera anlatılanlara aldanmayın ...   0.0
1      Alacak arkadaşlara önemli hatırlatma fatura gö...   0.0
2      Daha öncede alışveriş yapmıştım  çok geç kargo...   0.0
3      2 ay içerisinde 2 kez servise gönderilen bir c...   0.0
4      İşlemcisi kötü hiç bir uygulama açık değilken ...   0.0
...                                                  ...   ...
47939                             Kaliteli ve kullanışlı   1.0
47940          kurulumu paketleme harika düşünmeden alın   1.0
47941                               kurulumu çok pratik.   1.0
47942                 üründen memnun kaldık.teşekkürler.   1.0
47943  Ürün şahane bir şekilde geldi. Üzerine 2 tane ...   1.0

[47944 rows x 2 columns]

In [11]:
df=shuffle(df)

In [12]:
df

                                                   yorum  puan
19628  Beğendim 10 numara 8-9 bilgisayara kadar gider...   1.0
25204                 Urun kalitesi on numara bes yildiz   1.0
32437              ürün güzel ama şarj kablosu kalitesiz   1.0
4628   Ürünü kartona sarıp göndermek yerine streçe sa...   0.0
3868   Dakikalarca uğraşmama rağmen aracım da sadece ...   0.0
...                                                  ...   ...
38339  fiyatı gerçekten çok uygun kalitesi güzel yoru...   1.0
14764  Ürünler kaliteli ve renkler çok canlı. Sarı ve...   1.0
24670  3 adet aldım. Sanırım daha sonrada siparişe de...   1.0
40717  Gerçekten çok çok çok çok çok  teşekkür ediyor...   1.0
44283  bu fiyata  bu kadar kaliteli olmasını beklemem...   1.0

[47944 rows x 2 columns]

In [13]:
df.to_csv('sonyorum.csv',index=False)